# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef8f9c9f9472fe4b152ca960f3746d9027625af835f597a429bd93a2995b283f5539e9f6a285d625817a4b4ac1c6722d1b70913cffc7d73f0f43c083395d3a7

test:
  secret_key_base: 7ac8b0c241ed9dc40ffe40d90abce82f74e9085bb88ec0f646e7cae30707bbf1a0b0de8f59cc96af807ffad0c7b52d48245b21510332fe5c986a4503bf417286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
